apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: attacker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: kali-linux-small
  labels:
    app: kalilinux
spec:
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pv-claim
  containers:
  - name: kalilinux
    image: masjohncook/kalilinux-small 
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/root"
      name: pv-storage
  restartPolicy: Always

